name: 'App deploy action script to ENONIC XP'
description: 'Github action script to be used for app deployment'
inputs:
  url:
    description: 'URL to XP instance'
    required: true
  username:
    description: 'user name'
    required: false
  password:
    description: 'password of deploy user'
    required: false
  client_key:
    description: 'Client key, required only for MTLS session'
    required: false
  client_cert:
    description: 'Client cert, required only for MTLS session'
    required: false
  cred_file:
    description: 'A service account key represented as a JSON string, containing the properties "algorithm", "kid", "principalKey", and "privateKey", used to generate a JWT token for authentication'
    required: false
  app_jar:
    description: 'Path and name of the app to be deployed'
    required: false
runs:
  using: "composite"
  steps:
    - id: step1
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - id: step2
      name: "Copy credentials file"
#      env:
#        CRED_FILE: ${{ inputs.cred_file }}
      run: |
        if [ -n "${{ inputs.cred_file }}" ]; then
          echo "Using Service Account to authenticate with the server"
          SERVICE_ACCOUNT_KEY_FILE=$(mktemp /tmp/service-account-XXXXXX.json)
          echo -n "${{ inputs.cred_file }}" > "${SERVICE_ACCOUNT_KEY_FILE}"
        
          echo "ENONIC_CLI_CRED_FILE=${SERVICE_ACCOUNT_KEY_FILE}" >> $GITHUB_ENV
        fi
      shell: bash

    - run: |
        echo "ENONIC_CLI_CRED_FILE is: $ENONIC_CLI_CRED_FILE"
        
        docker run --rm \
        -e ENONIC_CLI_REMOTE_URL="${ENONIC_CLI_REMOTE_URL}" \
        -e ENONIC_CLI_REMOTE_USER="${ENONIC_CLI_REMOTE_USER}" \
        -e ENONIC_CLI_REMOTE_PASS="${ENONIC_CLI_REMOTE_PASS}" \
        enonic/enonic-ci:7.15 \
        enonic app install --help
      shell: bash
      env:
        ENONIC_CLI_REMOTE_URL: ${{ inputs.url }}
        ENONIC_CLI_REMOTE_USER: ${{ inputs.username }}
        ENONIC_CLI_REMOTE_PASS: ${{ inputs.password }}

#    - name: 'Deploy apps'
#      uses: docker://enonic/enonic-ci:7.15
#      with:
#        entrypoint: ./entrypoint.sh
#        args: bash -c "enonic --version"
#      env:
#        ENONIC_CLI_REMOTE_URL: 'http://localhost:4848'
