on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Remote URL to XP instance'
        required: true
        type: string
        default: 'http://localhost:8080'
      http_proxy_url:
        description: 'URL of proxy server to use'
        required: false
        type: string
      app_jar:
        description: 'Path and name of the app to be deployed'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - id: build-and-publish
        uses: enonic-playground/action-sandbox@main
        with:
          url: ${{ inputs.url }}
          app_jar: ${{ inputs.app_jar }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          cred_file: ${{ secrets.SA_CRED_FILE }}
#          client_key: ${{ secrets.DEPLOY_CLIENT_KEY }}
#          client_cert: ${{ secrets.DEPLOY_CLIENT_CERT }}
