on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Remote URL to XP instance'
        required: true
        type: string
        default: 'http://localhost:8080'
      username:
        description: 'User name to XP instance'
        required: true
        type: string
      password:
        description: 'Password to XP instance'
        required: true
        type: string
      cred_file:
        description: 'A service account key represented as a JSON string, containing the properties "algorithm", "kid", "principalKey", and "privateKey", used to generate a JWT token for authentication'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Make entrypoint executable
        run: chmod +x entrypoint.sh
      - id: build-and-publish
        uses: enonic-playground/action-sandbox@main
        with:
          url: ${{ inputs.url }}
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}
